name: sci_python

channels:
 - conda-forge
 - anaconda
 
dependencies:
- python=3.6
- autograd
- basemap
- bokeh
- ipython
- jupyter
- jupyterlab
- notebook
- ipyparallel
- ipywidgets
- jupyter_client
- jupyter_core
- numpy
- pandas
- patsy
- pillow
- pprofile
- python-graphviz
- pydot
- pyparsing
- pyzmq
- rpy2  
- scikit-learn
- scipy
- seaborn
- snakeviz
- xlrd
- pip:
    - yellowbrick