name: sci_python
channels:
 - conda-forge
 - anaconda
dependencies:
- python=3.6
- autograd
- basemap
- beautifulsoup4
- bokeh
- ipython
- jupyter
- jupyterlab
- notebook
- ipyparallel
- ipywidgets
- jupyter_client
- jupyter_core
- lxml
- networkx
- numpy
- pandas
- patsy
- Pillow
- pip
- pprofile
- python-graphviz
- pyparsing
- pyzmq
- rpy2
- scikit-learn
- scikit-image
- scipy
- seaborn
- six
- snakeviz
- sympy
- toolz
- xlrd
- pip:
    - yellowbrick
    - notedown>=1.5
    - jupytercontrib>=0.0.5
    - bs4
    - git+https://github.com/networkx/networkx.git
    - git+https://github.com/nlhepler/pydot.git
